spring.application.name=demo
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:file:./data/demo-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring:
datasource:
url: jdbc:h2:mem:testdb
driver-class-name: org.h2.Driver
username: sa
password:

h2:
console:
enabled: true

jpa:
hibernate:
ddl-auto: update
show-sql: true